const S = ['HP', 'ATK', 'DEF', 'SPD', 'INT', 'MAG'];
const stat = (hp, atk, def, spd, int, mag) => ({ HP: hp, ATK: atk, DEF: def, SPD: spd, INT: int, MAG: mag });
const zero = stat(0, 0, 0, 0, 0, 0);

const rankHeights = {
  'Coal': ['5.2 Low Servant', "6'0\""], 'Richterite': ['5.2 Low Servant', "3'11\""], 'Salt': ['5.2 Low Servant', "3'0\""],
  'Pearl': ['5.1 High Servant', "6'0\""], 'Spinel': ['5.1 High Servant', "5'3\""],
  'Cavansite': ['4.3 Service Trade', "3'9\""], 'Iron': ['4.3 Service Trade', "4'1\""], 'Copper': ['4.3 Service Trade', "4'3\""], 'Bronze': ['4.3 Service Trade', "6'2\""], 'Graphene': ['4.3 Service Trade', "1'0\""],
  'Lapis': ['4.2 Median Service Trade', "5'10\""], 'Malachite': ['4.2 Median Service Trade', "7'10\""], 'Yooperlite': ['4.2 Median Service Trade', "5'11\""], 'Clinohumite': ['4.2 Median Service Trade', "5'10\""], 'Calcite': ['4.2 Median Service Trade', "5'6\""], 'Selenite': ['4.2 Median Service Trade', "11'0\""], 'Bismuth': ['4.2 Median Service Trade', "6'8\""], 'Verdelite': ['4.2 Median Service Trade', "5'10\""], 'Silver': ['4.2 Median Service Trade', "5'10\""], 'Tektite': ['4.2 Median Service Trade', "5'11\""], 'Tivcral': ['4.2 Median Service Trade', "4'7\""], 'Chromium': ['4.2 Median Service Trade', "6'4\""], 'Cobalt': ['4.2 Median Service Trade', "6'6\""], 'Nephrite': ['4.2 Median Service Trade', "6'4\""], 'Sunstone': ['4.2 Median Service Trade', "5'10\""], 'Turquoise': ['4.2 Median Service Trade', "6'8\""], 'Goshenite': ['4.2 Median Service Trade', "7'8\""],
  'Zircon': ['4.1 High Service Trade', "6'1\""], 'Angelite': ['4.1 High Service Trade', "5'11\""], 'Rutile': ['4.1 High Service Trade', "5'11\""], 'Willemite': ['4.1 High Service Trade', "5'10\""], 'Opal': ['4.1 High Service Trade', "6'0\""], 'Steel': ['4.1 High Service Trade', "8'1\""], 'Tungsten': ['4.1 High Service Trade', "9'0\""], 'Stellite': ['4.1 High Service Trade', "7'2\""], 'Serpentine': ['4.1 High Service Trade', "7'6\""],
  'Eucryptite': ['3.3 Low Militia', "4'3\""], 'Ruby': ['3.3 Low Militia', "3'10\""], 'Aragonite': ['3.3 Low Militia', "5'2\""], 'Prasiolite-Goshenite': ['3.3 Low Militia', "8'1\""], 'Quartz': ['3.2 Median Militia', "8'0\""], 'Amethyst': ['3.2 Median Militia', "8'0\""], 'Aventurine': ['3.2 Median Militia', "8'0\""], 'Blue Quartz': ['3.2 Median Militia', "8'0\""], 'Carnelian': ['3.2 Median Militia', "8'0\""], 'Cherry Quartz': ['3.2 Median Militia', "8'0\""], 'Citrine': ['3.2 Median Militia', "8'0\""], 'Jasper': ['3.2 Median Militia', "8'0\""], 'Milky Quartz': ['3.2 Median Militia', "8'0\""], 'Prasiolite': ['3.2 Median Militia', "8'0\""], 'Rose Quartz': ['3.2 Median Militia', "8'0\""], 'Smoky Quartz': ['3.2 Median Militia', "8'0\""], 'Zebra Jasper': ['3.2 Median Militia', "8'0\""], 'Obsidian': ['3.2 Median Militia', "8'0\""], 'Titanium': ['3.1 High Militia', "9'0\""], 'Topaz': ['3.1 High Militia', "8'10\""],
  'Azurite': ['2.3 Low Authoritative/Aristocrat', "5'10\""], 'Agate': ['2.3 Low Authoritative/Aristocrat', "7'4\""], 'Aquamarine': ['2.3 Low Authoritative/Aristocrat', "3'0\""], 'Jade': ['2.3 Low Authoritative/Aristocrat', "6'0\""], 'Fluorite': ['2.3 Low Authoritative/Aristocrat', "8'4\""], 'Morganite': ['2.3 Low Authoritative/Aristocrat', "3'11\""], 'Amber': ['2.3 Low Authoritative/Aristocrat', "3'0\""], 'Onyx': ['2.3 Low Authoritative/Aristocrat', "8'0\""], 'Polyhedroid Agate': ['2.3 Low Authoritative/Aristocrat', "8'0\""],
  'Nacre': ['2.2 Median Authoritative/Aristocrat', "9'2\""], 'Kyanite': ['2.2 Median Authoritative/Aristocrat', "8'2\""], 'Scapolite': ['2.2 Median Authoritative/Aristocrat', "8'1\""], 'Gold': ['2.2 Median Authoritative/Aristocrat', "7'1\""], 'Charoite': ['2.2 Median Authoritative/Aristocrat', "6'0\""], 'Emerald': ['2.2 Median Authoritative/Aristocrat', "8'1\""], 'Platinum': ['2.2 Median Authoritative/Aristocrat', "8'4\""], 'Rhodochrosite': ['2.2 Median Authoritative/Aristocrat', "8'4\""], 'Hessonite': ['2.1 High Authoritative/Aristocrat', "7'8\""], 'Pyrope': ['2.1 High Authoritative/Aristocrat', "7'10\""], 'Demantoid': ['2.1 High Authoritative/Aristocrat', "5'10\""], 'Zoisite': ['2.1 High Authoritative/Aristocrat', "8'0\""], 'Sapphire': ['2.1 High Authoritative/Aristocrat', "3'10\""],
  'Cubic Zirconia': ['1.2 Transcendent', 'Diamond dependent'], 'Diamond Pearl': ['1.2 Transcendent', "6'2\""], 'Diamond Spinel': ['1.2 Transcendent', "5'5\""], 'Celestine': ['United Frontier', "7'2\""], 'Almandine': ['United Frontier', "9'0\""],
};

const add = (name, values, ability, extras = {}) => ({ name, faction: 'Gempire', stats: stat(...values), abilities: [ability], ...extras });
const gems = [
  add('Coal', [32,5,6,4,4,1], 'Body Heat'), add('Richterite', [30,4,5,5,5,7], 'Light Tools'), add('Salt', [16,2,2,5,4,1], 'Fusion Boost'), add('Pearl', [26,4,3,5,5,6], 'Pocket Space; Holographic Projection', { hidden: ['Holo-Pearls', 'Elemental Affinity'] }), add('Spinel', [32,6,6,6,5,6], 'Stretchy Body'), add('Cavansite', [28,7,4,4,4,1], 'Heavy Lift'), add('Iron', [44,6,12,4,4,1], 'Tough Body', { kind: 'Metal' }), add('Copper', [36,5,8,4,5,3], 'Power Channel', { kind: 'Metal' }), add('Bronze', [40,5,10,4,6,1], 'Blueprint Mind', { kind: 'Metal' }), add('Graphene', [20,3,9,6,6,5], 'Shrink Down'),
  add('Lapis', [36,4,8,5,5,10], 'Water Control'), add('Malachite', [28,4,4,5,5,9], 'Earth Shaping; Toxin Soak', { tags: ['Non-fusion'] }), add('Yooperlite', [30,5,5,5,5,8], 'Lava Generation & Shaping'), add('Clinohumite', [34,7,7,5,5,6], 'Fire Control; Heat Resist'), add('Calcite', [26,3,3,5,8,7], 'Calm Presence'), add('Selenite', [26,3,3,4,6,9], 'Empathy'), add('Bismuth', [32,5,6,4,5,3], 'No listed special'), add('Verdelite', [30,8,5,5,5,6], 'No listed special'), add('Silver', [32,4,6,5,5,3], 'Electricity Generation', { kind: 'Metal' }), add('Tektite', [26,5,3,6,5,1], 'Scout Sense'), add('Tivcral', [26,3,3,16,5,6], 'Quick Stop; Wind Cutter; Speed Strike', { kind: 'Metal', hidden: ['Gearshift'] }), add('Chromium', [38,9,9,5,5,7], 'Harden Touch', { kind: 'Metal' }), add('Cobalt', [42,6,11,5,5,8], 'Magnetic Field', { kind: 'Metal' }), add('Nephrite', [26,6,3,6,6,1], 'Natural Pilot'), add('Turquoise', [28,6,4,5,6,5], 'No listed special'),
  add('Eucryptite', [28,6,4,6,5,1], 'Luminescence'), add('Ruby', [26,10,3,5,5,4], 'Limited Calokinesis'), add('Aragonite', [26,4,3,6,4,1], 'Dogfight Instinct'), add('Prasiolite-Goshenite', [32,8,6,5,8,9], 'Cryophrenia', { tags: ['Geode'], hidden: ['Minor Technopathy'] }), add('Titanium', [43,10,11,5,5,5], 'Shield Summoning', { kind: 'Metal' }), add('Topaz', [38,9,9,5,5,3], 'Shockwave Pulse', { hidden: ['Shockwave Pulse'] }),
  add('Azurite', [26,4,3,5,6,5], 'Hydrokinetic Constructs', { hidden: ['Hydrokinetic Constructs'] }), add('Agate', [32,6,6,5,6,4], 'Commanding Presence', { hidden: ['Commanding Presence'] }), add('Aquamarine', [28,9,4,8,6,6], 'Hydrokinetic Combat; Fairy Wings', { hidden: ['Cryokinesis'] }), add('Jade', [30,6,5,5,5,1], 'No listed special'), add('Fluorite', [36,6,8,5,6,2], 'Luminescence; Limited ESP', { hidden: ['Luminescence', 'Limited ESP'] }), add('Morganite', [28,9,4,5,6,8], 'Bubble Craft', { hidden: ['Bubble Craft'] }), add('Amber', [30,4,5,8,5,6], 'Oposkinetic Combat; Bee Wings', { hidden: ['Melikinesis'] }), add('Onyx', [36,8,8,5,6,2], 'Weapon Mastery', { hidden: ['Weapon Mastery'], tags: ['Agate subtype'] }), add('Polyhedroid Agate', [32,6,6,5,6,8], 'Restoration', { tags: ['Agate subtype', 'Geode'] }),
  add('Nacre', [26,4,3,5,6,10], 'Life Giver; Repair Station'), add('Kyanite', [32,6,6,4,7,9], 'Veritas Sense'), add('Scapolite', [30,6,5,5,5,8], 'Resonating Voice'), add('Charoite', [30,6,5,5,6,9], 'Power Boost'), add('Emerald', [40,10,10,5,6,9], 'Terrifying Aura'), add('Platinum', [40,5,10,5,6,1], 'No listed special', { kind: 'Metal' }), add('Rhodochrosite', [30,4,5,5,6,10], 'Holo Design'), add('Hessonite', [38,9,9,5,5,8], 'Commanding Aura', { hidden: ['Commanding Aura'] }), add('Pyrope', [34,9,7,5,5,7], 'Silence; Levitation'), add('Demantoid', [32,9,6,5,8,1], 'No listed special'), add('Zoisite', [32,9,6,5,9,9], 'Essence Chemistry'), add('Sapphire', [28,10,4,5,7,10], 'Clairvoyance; Limited Cryokinesis'),
  add('Cubic Zirconia', [48,16,14,5,9,14], 'Sub-Domain', { tags: ['Transcendent'] }), add('Diamond Pearl', [34,6,7,5,6,9], 'Fragment', { tags: ['Pearl subtype', 'Transcendent'] }), add('Diamond Spinel', [40,8,7,6,6,9], 'Cartoon Physics', { tags: ['Spinel subtype', 'Transcendent'] }),
  add('Watermelon Tourmaline', [26,3,3,5,6,7], 'Bond Reading', { hidden: ['Heart to Heart'], height: "5'8\"" }), add('Brown Tourmaline', [38,6,9,4,4,2], 'Ground and Anchor', { hidden: ['Sturdy Frame'], height: "7'2\"" }), add('Blue Tourmaline', [27,9,3,7,7,6], 'Electrokinetic Transfer and Manipulation', { height: "6'2\"" }), add('Green Tourmaline', [30,4,5,5,5,7], 'Plant Generation & Shaping', { hidden: ['Ecological Empathy'], height: "5'8\"" }), add('Black Tourmaline', [40,8,10,5,5,3], 'Barrier Summoning', { hidden: ['Fear Proof Induction'], height: "7'6\"" }), add('Pink Tourmaline', [28,4,4,5,7,9], 'Set the Scene', { hidden: ['Ear to the Ground'], height: "5'8\"" }), add('Dragon’s Breath Fire Opal', [36,10,8,5,6,9], 'Dragon’s Breath; Scaled Hide', { hidden: ['Heat Sense'], height: "7'2\"" }), add('Shattuckite', [26,5,6,5,7,4], 'Persuasive Talking; Perfect Vocabulary', { height: "6'0\"" }), add('Chrysoberyl', [30,4,5,5,6,4], 'Perfect Palate', { hidden: ['Warm Touch'], height: "5'9\"" }), add('Larimar', [30,4,5,5,6,9], 'Ice Carving; Frost Terraform', { height: "6'2\"" }), add('Catseye', [31,6,11,7,5,4], 'Cat-like Reflexes; Contortionist', { hidden: ['Liquidation'], height: "5'7\"" }),
  add('Zircon', [26,5,3,5,7,1], 'Sharp Case'), add('Angelite', [28,3,4,5,6,8], 'Healing Essence'), add('Rutile', [26,6,3,6,7,1], 'Site Sense'), add('Willemite', [26,6,3,6,6,4], 'Wide Watch'), add('Opal', [34,7,7,5,8,6], 'Endless Library', { tags: ['Non-fusion'] }), add('Steel', [38,6,9,5,5,4], 'Containment Field', { kind: 'Metal', hidden: ['Containment Field'] }), add('Tungsten', [46,8,13,3,5,3], 'Heat Proof', { kind: 'Metal' }), add('Stellite', [44,9,12,5,8,8], 'Upgrade & Merge', { kind: 'Metal' }), add('Serpentine', [28,4,4,5,8,5], 'Close Study', { tags: ['Non-fusion'], hidden: ['Steady Hands'] }),
  add('Quartz', [30,7,5,5,4,1], 'Tall and Tough', { tags: ['Quartz group'] }), add('Amethyst', [30,7,5,5,5,3], 'Purple Flame Generation', { tags: ['Quartz subtype'], hidden: ['Purple Flame Generation'] }), add('Aventurine', [30,7,5,5,5,4], 'Limited Plant Generation & Shaping', { tags: ['Quartz subtype'], hidden: ['Limited Plant Generation & Shaping'] }), add('Blue Quartz', [30,7,5,5,5,5], 'Cool Waters', { tags: ['Quartz subtype'], hidden: ['Cool Waters'] }), add('Carnelian', [30,7,5,5,5,3], 'Sand Play', { tags: ['Quartz subtype'], hidden: ['Sand Play'] }), add('Cherry Quartz', [28,8,4,5,5,1], 'No listed special', { tags: ['Quartz subtype'] }), add('Citrine', [28,7,4,5,5,2], 'Oxidation Inducement', { tags: ['Quartz subtype'], hidden: ['Oxidation Inducement'] }), add('Jasper', [34,8,7,5,4,1], 'No listed special', { tags: ['Quartz subtype'] }), add('Milky Quartz', [30,7,5,4,5,2], 'Limited Sleep Induction', { tags: ['Quartz subtype'], hidden: ['Limited Sleep Induction'] }), add('Prasiolite', [30,7,5,5,6,4], 'Limited Technokinesis', { tags: ['Quartz subtype'], hidden: ['Limited Technokinesis'] }), add('Rose Quartz', [30,7,5,5,5,3], 'Empathy', { tags: ['Quartz subtype'], hidden: ['Empathy'] }), add('Smoky Quartz', [30,7,5,5,5,3], 'Vibration Generation', { tags: ['Quartz subtype', 'Non-fusion'], hidden: ['Vibration Generation'] }), add('Zebra Jasper', [32,8,6,5,5,2], 'Echolocation', { tags: ['Quartz subtype'], hidden: ['Echolocation'] }),
  add('Peridot, Era 0', [32,9,6,5,7,3], 'Tech Speak; Metal Control', { hidden: ['Technotravel'], height: "7'6\"" }), add('Peridot, Era 1', [30,5,5,5,7,6], 'Metal Control', { hidden: ['Technopathy'], height: "5'10\"" }), add('Peridot, Era 2A', [30,5,5,5,7,3], 'Metal Control', { hidden: ['Metal Control'], height: "4'4\"" }), add('Gold, Era 0-1', [36,5,8,5,5,6], 'Gold Control; Pure Complexion', { kind: 'Metal' }), add('Gold, Era 2A', [32,4,6,5,7,7], 'Child of the Sun God; Fine Complexion', { kind: 'Metal', height: "6'3\"" }), add('Bronze, Era 0-1', [42,6,11,4,9,3], 'Structural Analysis', { kind: 'Metal', height: "6'2\"" }), add('Hematite, Era 0', [32,9,6,5,6,11], 'Push Broadcast', { height: "7'11\"" }), add('Hematite, Era 2', [34,8,7,5,6,10], 'Memory Wipe', { height: "8'2\"" }), add('Hessonite, Era 0', [36,10,8,6,7,10], 'Personal Darkness', { height: "9'2\"" }), add('Sunstone, Era 1B', [26,6,3,5,8,9], 'Deep Insight; Fire Power'), add('Goshenite, Era 0', [28,9,4,5,8,8], 'Plasma Control', { hidden: ['Full Read'] }), add('Obsidian', [32,8,6,5,5,3], 'Lava Shaping', { hidden: ['Lava Shaping'] }),
  { name: 'Sphene', faction: 'Gempire', stats: zero, fusion: true, components: 'Pearl + Peridot', rank: '4.2 Median Service Trade', height: "11'10\"", abilities: ['Holographic Projection; Metal Control; Holo-Sphene; Pocket Space'], hidden: ['Elemental Affinity'] },
  { name: 'Moonstone', faction: 'Gempire', stats: zero, fusion: true, components: 'Lapis + Pearl', rank: '3.3 Low Militia', height: "14'0\"", abilities: ['Water Control; Pocket Space; Holographic Projection; Holo-Moonstone'], hidden: ['Elemental Affinity'] },
  { name: 'Malachite, Fusion', faction: 'Gempire', stats: zero, fusion: true, components: 'Lapis + Quartz subtype', rank: '3.2 Median Militia', height: "13'10\"", abilities: ['Water Control; Tall and Tough; selected Quartz subtype ability'] },
  { name: 'Rhodonite', faction: 'Gempire', stats: zero, fusion: true, components: 'Ruby + Pearl', rank: '3.2 Median Militia', height: "9'10\"", abilities: ['Fire Generation; Big Jump; Holographic Projection; Holo-Rhodonite; Pocket Space; Fireball'], hidden: ['Elemental Affinity'] },
  { name: 'Garnet', faction: 'Gempire', stats: zero, fusion: true, components: 'Ruby + Sapphire', rank: '2.2 Median Authoritative/Aristocrat', height: "7'8\"", abilities: ['Clairvoyance; Limited Cryokinesis; Limited Calokinesis'] },
  { name: 'Green Serpentine', faction: 'Gempire', stats: zero, fusion: true, components: 'Scapolite + Lapis', rank: '2.2 Median Authoritative/Aristocrat', height: "13'11\"", abilities: ['Hypnotic Voice; Serpent Shift'], hidden: ['Voice Copy; Voice Steal'] },
  { name: 'Sardonyx, Pyrope Variant', faction: 'Gempire', stats: zero, fusion: true, components: 'Pyrope + Pearl', rank: '2.1 High Authoritative/Aristocrat', height: "13'10\"", abilities: ['Crowd Pleaser; Silence; Holographic Projection; Holo-Sardonyx; Pocket Space; Levitation'], hidden: ['Elemental Affinity'] },
  { name: 'Sardonyx, Hessonite Variant', faction: 'Gempire', stats: zero, fusion: true, components: 'Hessonite + Pearl', rank: '2.1 High Authoritative/Aristocrat', height: "13'8\"", abilities: ['Crowd Pleaser; Holographic Projection; Holo-Sardonyx; Pocket Space'], hidden: ['Commanding Aura; Elemental Affinity'] },
  { name: 'Tanzanite', faction: 'Gempire', stats: zero, fusion: true, components: 'Sapphire + Pearl', rank: '2.1 High Authoritative/Aristocrat', height: "9'10\"", abilities: ['Clairvoyance; Pocket Space; Holographic Projection; Holo-Tanzanite'], hidden: ['Vision Cast; Elemental Affinity'] },
];

const quartz = [
  ['Amethyst', [2,2,-1,0,-1,1], 'Plasma Generation'], ['Aventurine', [1,-1,1,0,0,2], 'Plant Generation & Shaping'], ['Blue Quartz', [0,-1,-1,1,0,3], 'Minor Hydrokinesis; Minor Cryokinesis'], ['Carnelian', [1,1,0,0,0,-2], 'Grit Skin'], ['Cherry Quartz', [-2,-1,-1,0,5,-1], 'Sharp Eye'], ['Citrine', [-2,1,-1,0,0,2], 'Citric Secretion'], ['Jasper', [4,2,2,-1,-1,-2], 'Stoneguard'], ['Milky Quartz', [2,-1,1,-2,0,0], 'Milky Mist'], ['Prasiolite', [0,-1,0,0,2,1], 'Assembly'], ['Rose Quartz', [1,-1,0,0,0,1], 'Empathy'], ['Smoky Quartz', [2,0,1,-1,0,0], 'Vibrokinesis'], ['Zebra Jasper', [4,4,0,0,-3,-2], 'Ergokinetic Combat; Herd Bond']
].map(([name, values, ability]) => ({ name, faction: 'United Frontier', modifier: stat(...values), abilities: [ability] }));

const frontier = [
  { name: 'Celestine', stats: stat(34,3,7,5,9,11), abilities: ['Advanced Restoration; Wingless Flight'] }, { name: 'Almandine', stats: stat(28,9,4,6,7,11), abilities: ['Psionics'], hidden: ['Small Flame'] }, { name: 'Yellow Tourmaline', stats: stat(28,5,4,5,7,4), abilities: ["Appraiser's Eye"], hidden: ['Golden Tongue'], height: "5'8\"" }, { name: 'Seraphinite', stats: stat(36,5,7,6,9,11), abilities: ['Perfect Restoration; Flight'], height: "7'4\"" }, { name: 'Iolite', stats: stat(28,3,4,5,9,3), abilities: ['Clarity Voice'], hidden: ['Memory Anchors'], height: "5'7\"" }, { name: 'Astrophyllite', stats: stat(28,3,4,5,8,4), abilities: ['Path Sense'], hidden: ['Serene Presence'], height: "5'9\"" }, { name: 'Labradorite', stats: stat(28,3,4,5,7,5), abilities: ['Record Keeper; Hydroportation'], height: "5'10\"" }, { name: 'Clear Quartz', stats: stat(30,6,5,5,5,3), abilities: ['Prism'], height: "8'0\"" }
].map(x => ({ ...x, faction: 'United Frontier' }));

const modifiers = [
  { name: 'No modifier', stats: zero, abilities: [] }, { name: 'Era 0', stats: stat(4,2,1,0,2,3), abilities: ['Perfect Shapeshifting'] }, { name: 'Era 0 Side-B', stats: stat(4,1,1,0,2,4), abilities: ['Skinwalker'] }, { name: 'Era 1A', stats: stat(2,1,0,0,0,-1), abilities: ['Essence Buster; Enhanced Shapeshifting'] }, { name: 'Era 1B', stats: stat(2,-1,0,1,2,1), abilities: ['Enhanced Senses; Weak Essence Buster'] }, { name: 'Era 2A', stats: stat(1,-1,-1,1,1,2), abilities: ['Emotion Fuels Power'] }, { name: 'Era 0-1 Metal Society', stats: stat(3,1,2,0,0,-1), abilities: ['Material Conductivity'], metalsOnly: true },
  { name: 'Theta Gold Sole Essence', stats: stat(3,2,1,0,2,2), abilities: ['True Essence Buster'], unique: true }, { name: 'Epsilon Blue Sole Essence', stats: stat(3,1,2,0,3,2), abilities: ['Absolute Sense'], unique: true }, { name: 'Nightshade Violet Sole Essence', stats: stat(3,1,2,1,2,2), abilities: ['Blind Spot Sense'], unique: true }, { name: 'Maroon Red Sole Essence', stats: stat(4,3,2,0,1,1), abilities: ['Unbreakable Line'], unique: true }, { name: 'Emerald Green Sole Essence', stats: stat(3,1,2,0,3,2), abilities: ['Restriction Bypass'], unique: true }, { name: 'Saturn Light Sole Essence', stats: stat(3,1,1,2,1,3), abilities: ['Surface Adherence'], unique: true }
];
const cuts = { Normal: { stats: zero, abilities: [] }, 'Perfect Cut': { stats: stat(3,2,2,1,1,3), abilities: [] }, 'Perfect Polish': { stats: stat(4,3,3,0,1,1), abilities: [] }, Defective: { stats: stat(-4,-2,-1,-1,-1,-3), abilities: ['Flawed Signature'] } };

const $ = id => document.getElementById(id); const factionEl = $('faction'), gemEl = $('gem'), prismEl = $('prism'), eraEl = $('era'), cutEl = $('cut'), fusionAEl = $('fusion-a'), fusionBEl = $('fusion-b');
function option(value, label = value) { const node = document.createElement('option'); node.value = value; node.textContent = label; return node; }
function choices(el, items, label = x => x) { el.replaceChildren(...items.map(x => option(typeof x === 'string' ? x : x.name, label(x)))); }
function activeRecord() { return [...gems, ...frontier].find(g => g.name === gemEl.value && g.faction === factionEl.value); }
function isService(rank) { return rank?.includes('Servant') || rank?.includes('Service Trade'); }
function rankFor(record) { return rankHeights[record.name]?.[0] || record.rank || (record.faction === 'United Frontier' ? 'United Frontier' : 'Not assigned'); }
function heightFor(record) { return record.height || rankHeights[record.name]?.[1] || 'Not assigned'; }
function jobBonus(rank, cut) { if (!cut.startsWith('Perfect')) return zero; if (rank.includes('Servant')) return stat(0,0,0,1,0,0); if (rank.includes('Service Trade')) return stat(0,0,1,0,0,0); if (rank.includes('Militia')) return stat(0,1,0,0,0,0); if (rank.includes('Authoritative')) return stat(0,0,1,0,0,0); if (rank.includes('Aristocrat')) return stat(0,0,0,0,0,1); if (rank.includes('Transcendent')) return stat(0,0,0,0,0,2); return zero; }
function combine(...sources) { const out = {}; S.forEach(k => out[k] = sources.reduce((sum, s) => sum + (s[k] || 0), 0)); return out; }
function enhanceFirstAbility(abilities) { const upgraded = [...abilities]; if (!upgraded.length || upgraded[0] === 'No listed special') return upgraded; const parts = upgraded[0].split(';').map(part => part.trim()); parts[0] = `Enhanced ${parts[0]}`; upgraded[0] = parts.join('; '); return upgraded; }
function levelGrowth(level, classification = 'Gem') { const gained = Math.max(0, level - 1); return stat(gained * 4, gained * 2, Math.floor(gained / 2), Math.floor(gained / 4), 0, gained * (classification === 'Organic' ? 2 : 4)); }
function totalExpForLevel(level) { let total = 0; for (let current = 2; current <= level; current += 1) total += 100 + (current - 2) * 25; return total; }
function expToNextLevel(level) { return level >= 30 ? null : 100 + (level - 1) * 25; }
function refreshGems() { const selected = gemEl.value; const list = [...gems, ...frontier].filter(g => g.faction === factionEl.value).sort((a,b) => a.name.localeCompare(b.name)); choices(gemEl, list, g => g.name); if (list.some(g => g.name === selected)) gemEl.value = selected; refresh(); }
function fusionId(record) { return `${record.faction}|${record.name}`; }
function fusionComponent(el) { return [...gems, ...frontier].find(record => fusionId(record) === el.value); }
function listAbilities(record) { return [...record.abilities, ...(record.hidden || []).map(ability => `Hidden: ${ability}`)]; }
function populateFusionSelect(el, selected) { const records = [...gems, ...frontier].filter(record => !record.fusion).sort((a, b) => `${a.faction}:${a.name}`.localeCompare(`${b.faction}:${b.name}`)); el.replaceChildren(...records.map(record => { const node = option(fusionId(record), `${record.faction}: ${record.name}`); return node; })); if (records.some(record => fusionId(record) === selected)) el.value = selected; }
function showFusionAbilities(target, record) { target.replaceChildren(...listAbilities(record).map(text => { const item = document.createElement('li'); item.textContent = text; return item; })); }
function refreshFusion() { const first = fusionComponent(fusionAEl); const second = fusionComponent(fusionBEl); if (!first || !second) return; const combined = combine(first.stats, second.stats); $('fusion-a-name').textContent = `${first.name} abilities`; $('fusion-b-name').textContent = `${second.name} abilities`; $('fusion-stats').replaceChildren(...S.map(key => { const div = document.createElement('div'); div.className = 'stat'; div.innerHTML = `<span>${key}</span><strong>${combined[key]}</strong><div class="change">Base stat total</div>`; return div; })); showFusionAbilities($('fusion-a-abilities'), first); showFusionAbilities($('fusion-b-abilities'), second); }
function initialiseFusionTool() { const first = fusionAEl.value; const second = fusionBEl.value; populateFusionSelect(fusionAEl, first); populateFusionSelect(fusionBEl, second); if (!fusionAEl.value) fusionAEl.selectedIndex = 0; if (!fusionBEl.value) fusionBEl.selectedIndex = Math.min(1, fusionBEl.options.length - 1); refreshFusion(); }
function refresh() {
  const record = activeRecord(); if (!record) return;
  const prismActive = record.name === 'Clear Quartz' && record.faction === 'United Frontier'; $('prism-step').classList.toggle('hidden', !prismActive);
  const modifier = modifiers.find(m => m.name === eraEl.value) || modifiers[0];
  const rank = rankFor(record); let base = record.stats; let inherited = [];
  if (prismActive && prismEl.value !== 'Unshifted') { const shift = quartz.find(q => q.name === prismEl.value); base = combine(base, shift.modifier); inherited = shift.abilities; }
  const cut = cuts[cutEl.value]; const polishAllowed = record.kind === 'Metal'; const cutAllowed = record.kind !== 'Metal';
  if (cutEl.value === 'Perfect Polish' && !polishAllowed) cutEl.value = 'Perfect Cut'; if (cutEl.value === 'Perfect Cut' && !cutAllowed) cutEl.value = 'Perfect Polish';
  const level = Math.min(30, Math.max(1, Number.parseInt($('level').value, 10) || 1)); $('level').value = level;
  const cutData = cuts[cutEl.value]; const bonus = jobBonus(rank, cutEl.value); const growth = levelGrowth(level, record.classification); const final = combine(base, modifier.stats, cutData.stats, bonus, growth); const changes = combine(modifier.stats, cutData.stats, bonus, growth, prismActive && prismEl.value !== 'Unshifted' ? quartz.find(q => q.name === prismEl.value).modifier : zero);
  $('result-name').textContent = prismActive && prismEl.value !== 'Unshifted' ? prismEl.value : record.name; $('rank').textContent = rank; $('height').textContent = heightFor(record); $('result-level').textContent = `${level} / 30`; $('next-exp').textContent = expToNextLevel(level) === null ? 'Level cap reached' : expToNextLevel(level).toLocaleString(); $('total-exp').textContent = totalExpForLevel(level).toLocaleString();
  $('badges').replaceChildren(...[record.faction, ...(record.tags || []), modifier.unique ? 'Unique modifier' : ''].filter(Boolean).map(x => { const b = document.createElement('span'); b.textContent = x; return b; }));
  $('stats').replaceChildren(...S.map(key => { const div = document.createElement('div'); div.className = 'stat'; const delta = changes[key]; div.innerHTML = record.fusion ? `<span>${key}</span><strong>?</strong><div class="change">Component-derived</div>` : `<span>${key}</span><strong>${Math.max(0, final[key])}</strong><div class="change">${delta ? `${delta > 0 ? '+' : ''}${delta} modifier` : 'Base value'}</div>`; return div; }));
  const baseAbilities = prismActive && prismEl.value !== 'Unshifted' ? record.abilities.filter(ability => ability !== 'Prism') : record.abilities; const primaryAbilities = [...baseAbilities, ...inherited]; const standardAbilities = cutEl.value.startsWith('Perfect') ? enhanceFirstAbility(primaryAbilities) : primaryAbilities; const abilityList = [...standardAbilities, ...modifier.abilities, ...cutData.abilities, ...(record.hidden || []).map(a => `Hidden: ${a}`)]; $('abilities').replaceChildren(...abilityList.map(text => { const li = document.createElement('li'); li.textContent = text; return li; }));
  const notes = []; if (record.fusion) notes.push(`This fusion uses ${record.components}. Its source sheet says to use its two component stats, but the combination formula has not been supplied, so its final stats remain unresolved.`); if (modifier.unique) notes.push('Unique modifiers replace an era modifier and should only be used for approved case-by-case records.'); if (cutEl.value.startsWith('Perfect')) notes.push('Perfect Cut and Perfect Polish enhance the gem type’s first listed standard ability.'); if (cutEl.value === 'Defective') notes.push('Defective penalty transfers are not automated yet. Apply only the allowed transfers and do not reduce any stat below 0.'); if (record.name.includes('Era')) notes.push('This record already has an era-labelled stat block. Confirm whether its base stats should also receive the selected era modifier before using it in play.'); if (prismActive) notes.push('United Frontier Prism shifts apply their listed stat modifier to Clear Quartz base stats.'); notes.push('Level gains are included: +4 HP and +2 ATK each level, +1 DEF every 2 levels, +1 SPD every 4 levels, and +4 MAG each level for Gems.'); $('notice').textContent = notes.join(' ');
}
choices(factionEl, ['Gempire', 'United Frontier']); choices(eraEl, modifiers, m => m.name); choices(prismEl, ['Unshifted', ...quartz.map(q => q.name)]); choices(cutEl, Object.keys(cuts));
factionEl.addEventListener('change', refreshGems); [gemEl, prismEl, eraEl, cutEl, $('level')].forEach(el => el.addEventListener('input', refresh));
refreshGems();
fusionAEl.addEventListener('change', refreshFusion); fusionBEl.addEventListener('change', refreshFusion); initialiseFusionTool();
